// This script visualizes a small sample of the SPEI results generated by the R script.
// It has been updated to use a color palette that matches the India Drought Atlas.

// --- 1. Configuration: Define Asset Paths and Visualization ---

// IMPORTANT: Replace 'your-gee-project/assets/' with your actual GEE project path.
var assetBasePath = 'projects/cs5-pushkinmangla/assets/'; // Example: 'projects/ee-your-username/assets/'

// A map to link a display name to its specific GEE asset ID.
var assetMap = {
  'SPEI-1 (Jun 2015)': assetBasePath + 'SPEI1_138',
  'SPEI-1 (Jun 2017)': assetBasePath + 'SPEI1_162',
  'SPEI-3 (Jul-Sep 2015)': assetBasePath + 'SPEI3_2015_09',
  'SPEI-3 (Apr-Jun 2018)': assetBasePath + 'SPEI3_2018_06',
  'SPEI-12 (Annual 2015)': assetBasePath + 'SPEI12_2015',
  'SPEI-12 (Annual 2019)': assetBasePath + 'SPEI12_2019'
};

// --- NEW VISUALIZATION LOGIC TO MATCH INDIA DROUGHT ATLAS ---

// Define the discrete colors from the atlas legend
var atlasPalette = [
  '#8B0000', // Exceptional Extreme Drought
  '#FF0000', // Severe Drought
  '#FFA500', // Moderate Drought
  '#FFFF00', // Abnormal Drought
  '#FFFFFF'  // Normal / Wet
];

// Define the visualization parameters for the reclassified image
var visParams = {min: 0, max: 4, palette: atlasPalette};

// Get the Madhya Pradesh boundary first, as we will need it for clipping.
var states = ee.FeatureCollection("FAO/GAUL_SIMPLIFIED_500m/2015/level1");
var mp = states.filter(ee.Filter.eq('ADM1_NAME', 'Madhya Pradesh'));


// --- 2. Load, Reclassify, and Display Images ---

// Loop through the asset map, reclassify each image, and add it to the map
for (var name in assetMap) {
  var originalImage = ee.Image(assetMap[name]);
  
  // Reclassify the SPEI image into 5 discrete categories based on the atlas legend
  var classifiedImage = ee.Image(0) // Start with a base image of 0
    .where(originalImage.lte(-0.5).and(originalImage.gt(-0.8)), 3) // Abnormal
    .where(originalImage.lte(-0.8).and(originalImage.gt(-1.3)), 2) // Moderate
    .where(originalImage.lte(-1.3).and(originalImage.gt(-1.6)), 1) // Severe
    .where(originalImage.lte(-1.6), 0)                         // Exceptional Extreme
    .where(originalImage.gt(-0.5), 4);                          // Normal or Wet

  // --- FIX: Clip the classified image to the MP boundary ---
  // This will make all areas outside the state transparent.
  var finalImage = classifiedImage.clip(mp);

  // Add the newly clipped and colored image to the map
  // The 'false' argument makes the layer turned off by default.
  Map.addLayer(finalImage, visParams, name, false);
}

// --- 3. Add Context Layers ---

// Add the Madhya Pradesh boundary for reference
Map.addLayer(mp.style({color: 'black', fillColor: '00000000', width: 2}), {}, 'MP Boundary');

// Center the map on the study area
Map.setCenter(78.65, 23.5, 6);

print("Script finished. Check the 'Layers' tab to toggle the SPEI images on and off.");

